spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: mongodb+srv://sebas9:Halamadrid10@cluster0.2u8mg.mongodb.net/purely_cart_service?retryWrites=true&w=majority&appName=Cluster0
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
